### ISSUE TITLE
NCM::Filesystem::update_fstab can die without any error

### ISSUE THREAD

**Issue by ned21** [quattor/ncm-lib-blockdevices#59] opened 2015-12-09 14:54 UTC
Prior to the most recent commits:

```
    178     my $entry = join ("\t",
    179                         (exists $self->{label}?
    180                             "LABEL=$self->{label}":
    181                             $self->{block_device}->devpath),
    182                         $self->{mountpoint},
    183                         $self->{type},
    184                         $self->{mountopts} .
    185                             (!$self->{mount} ? ",noauto":""),
    186                             $self->{freq},
    187                         $self->{pass});
```

if $self->{block_device} is undef (e.g. due to #58) then this code just exits without any sort of user-visible indication.

I see in HEAD that the blockdevice code has moved to https://github.com/quattor/ncm-lib-blockdevices/blob/master/src/main/perl/Filesystem.pm#L178 but I would suspect the same problem exists that calling devpath on undef is being suppressed.

**Comment by ned21** [comment] 2015-12-09 15:24
Interestingly this did result in an error when running without debug/verbose:

```
# ncm-ncd --configure fstab

[INFO] NCM-NCD version 14.10.0 started by root at: Wed Dec  9 09:23:56 2015
[INFO] executing configure on components....


[INFO] running component: fstab
---------------------------------------------------------
[ERROR] component fstab executing method Configure fails: Can't call method "devpath" on an undefined value at /usr/lib/perl/NCM/Filesystem.pm line 176.

[ERROR] cannot execute configure on component fstab
```

Versus when run in --verbose and --debug mode:
```
2015/12/09-09:20:16 -----------------------------------------------------------
2015/12/09-09:20:16 [INFO] note: running component fstab in noaction mode
2015/12/09-09:20:16 [VERB] Opening file /etc/fstab
2015/12/09-09:20:16 [VERB] Updating /etc/fstab with new or modified contents
2015/12/09-09:20:16 [DEBUG] Update fstab entry at /d/ny20db49/d2
2015/12/09-09:20:16 [VERB] Not saving file /etc/fstab
2015/12/09-09:20:16 [VERB] Changes to /etc/fstab:
2015/12/09-09:20:16
2015/12/09-09:20:16 [INFO] configure on component fstab executed, 0 errors, 0 warnings
```

**Comment by stdweird** [comment] 2015-12-09 18:06
that's actually very bad... can you share both runs in debug like 
https://github.com/quattor/configuration-modules-core/issues/468#issuecomment-100830121

**Comment by stdweird** [comment] 2016-01-05 07:27
there was some pm with @ned21 to get detailed logs and some testing. the summary is as follows:

both runs (with and without --verbose/--debug) fail, and run within an eval in `ComponentProxy.pm` `_execute`.
in the non-verbose/debug case, this is "trapped" and error reported.

the failure happens when adding a line in `update_fstab` in `Filesystem` (the
`build()` from blockdevfactory returns undef, which is now reported/fixed
in #60)

perl fails, and first starts the `DESTROY` of the `FileEditor` instance
(it goes out of scope of `update_fstab`), triggering a `->close()`.

here's the catch:
with verbose/debug, `CAF/Reporter(Many)` `syslog` is called (as part of
the logging in `->close()`), which opens it's own `eval {}`, which does not
fail, and it resets the `$@` from the orignal eval in `ComponentProxy`.

altough i tried and failed to reproduce this, it seems to be a known issue
http://search.cpan.org/~ether/Try-Tiny-0.24/lib/Try/Tiny.pm#Clobbering_%24@

as suggested in the link, making the `$@` local should fix the issue.

this was tested and verified by @ned21  (the patch is as simple as adding 
```perl
local $@;
```
before the `eval {` in CAF `Reporter`.)

obviously, this should happen for all `eval {}` constructions in use, and not only for this one syslog call.

**Closed** 2016-01-11 17:26 UTC
